# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'rspec', :notification => true, :version => 2 do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec_helper.rb')  { "spec" }
  watch('../src/server/standards.rb')  { "standards_spec.rb" }
end